// Code generated by protoc-gen-go.
// source: github.com/mondough/mercury/testproto/dummy.proto
// DO NOT EDIT!

/*
Package testproto is a generated protocol buffer package.

It is generated from these files:
	github.com/mondough/mercury/testproto/dummy.proto

It has these top-level messages:
	DummyRequest
	DummyResponse
*/
package testproto

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type DummyRequest struct {
	Ping string `protobuf:"bytes,1,opt,name=ping" json:"ping,omitempty"`
}

func (m *DummyRequest) Reset()         { *m = DummyRequest{} }
func (m *DummyRequest) String() string { return proto.CompactTextString(m) }
func (*DummyRequest) ProtoMessage()    {}

type DummyResponse struct {
	Pong string `protobuf:"bytes,1,opt,name=pong" json:"pong,omitempty"`
}

func (m *DummyResponse) Reset()         { *m = DummyResponse{} }
func (m *DummyResponse) String() string { return proto.CompactTextString(m) }
func (*DummyResponse) ProtoMessage()    {}

func init() {
}
